
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/CardsRest
    username: root
    password: Johnda12#
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect




app:
  security:
    jwt:
      secretKey: 70337336763979244226452948404D635166546A576E5A7234743777217A2543
      expiration: 86400000       #a day
